version: "3"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 8081:80
  backend:
    build:
      context: ./
    ports:
      - 8082:80
  frontend:
    build:
      context: ./frontend/
