version: "3"

services:
  nginx:
    build:
      context: ./apps/nginx
    ports:
      - 8081:80
  backend:
    build:
      context: ./apps/backend
    working_dir: /app
    volumes:
      - ./apps/backend:/app
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
      - LOG_CHANNEL=stderr
      - APP_LOG=errorlog

  # Utility container that waits for MariaDB to be ready and executes migrations + seeders
  backend_seeder:
    image: docker.io/bitnami/laravel:7-debian-10
    command: ["/migrate-and-seed.sh"]
    working_dir: /app
    volumes:
      - ./apps/backend:/app:cached
      - ./apps/backend/util/docker/seeder.sh:/migrate-and-seed.sh:cached
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
      - LOG_CHANNEL=stderr
      - APP_LOG=errorlog
  frontend:
    build:
      context: ./apps/frontend/
    volumes:
      # Frontend is served from this directory. Remember to build it first though, using scripts in /frontend/package.json
      - ./apps/frontend/dist/my-first-project:/var/www/html/:cached

  mariadb:
    image: 'docker.io/bitnami/mariadb:10.2-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
